apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: skeletor
        image: skeletor
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: api
